web:
  build: .
  volumes:
    - .:/usr/src/app
    - data/media:/data/media
  ports:
    - "8000:8000"
  links:
    - "postgres:postgres"
  environment:
    SECRET_KEY: "this-should-be-long-and-random"
    DATABASE_URL: postgres://web:random-postgres-password@postgres:5432/web


postgresdata:
  # pure data container
  image: busybox
  volumes:
    - /etc/postgresql
    - /var/log/postgresql:/var/log/postgresql
    - /var/lib/postgresql


postgres:
  image: postgres:9.4.1
  volumes_from:
    - postgresdata
  environment:
    POSTGRES_USER: web
    POSTGRES_PASSWORD: "random-postgres-password"



